name: Dev CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      GRADLE_OPTS: -Dorg.gradle.jvmargs="-XX:MaxMetaspaceSize=2g"

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build
      run: ./gradlew clean assembleDebug

    - name: Test
      run: ./gradlew testDebugUnitTest

    - name: Lint
      run: ./gradlew lintDebug

#    - name: Detekt
#      run: ./gradlew downloadDetektConfig detekt

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-outputs
        path: app/build/outputs

    - name: Upload build reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build-reports
        path: |
          **/build/test-results/**/TEST-*.xml
          library/build/reports/*.html
          */build/reports/detekt/*.html
