name: Release CI

on:
  push:
    branches: [ release ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      GRADLE_OPTS: -Dorg.gradle.jvmargs="-XX:MaxMetaspaceSize=2g"

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
#        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }} # Value of the GPG private key to import
#        gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build
      run: ./gradlew clean assembleRelease

    - name: Test
      run: ./gradlew testReleaseUnitTest

    - name: Lint
      run: ./gradlew lintRelease

#    - name: Detekt
#      run: ./gradlew downloadDetektConfig detekt

    - name: Deploy
      env:
        MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      run: ./gradlew publishMavenPublicationToSoupbowlRepository publishMavenPublicationToMavenCentralRepository
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-outputs
        path: app/build/outputs

    - name: Upload build reports
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: build-reports
        path: |
          **/build/test-results/**/TEST-*.xml
          library/build/reports/*.html
          */build/reports/detekt/*.html
