name: Dev CI

on:
  push:
    branches: [ release ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      GRADLE_OPTS: -Dorg.gradle.jvmargs="-XX:MaxMetaspaceSize=2g"

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew clean build

      - name: Runs all checks (Test, Detekt, etc.)
        run: ./gradlew check

      - name: Deploy
        env:
          MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
        run: ./gradlew publishAllPublicationsToMavenCentralRepository

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-outputs
          path: app/build/outputs

      - name: Upload build reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-reports
          path: |
            **/build/test-results/**/TEST-*.xml
            library/build/reports/*.html
            */build/reports/detekt/*.html
